{% set name = "imgaug" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e1354d41921f1b306b50c5141b4870f17e81b531cae2f5c3093da9dc4dcb3cf4

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - six
    - numpy >=1.15
    - scipy
    - pillow
    - matplotlib
    - scikit-image >=0.14.2
    - opencv
    - imageio
    - shapely

test:
  imports:
    - imgaug

about:
  home: https://github.com/aleju/imgaug
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Image augmentation for machine learning experiments'

  description: |
    This python library helps you with augmenting images for your machine
    learning projects. It converts a set of input images into a new, much
    larger set of slightly altered images.
  doc_url: https://imgaug.readthedocs.io/
  dev_url: https://github.com/aleju/imgaug

extra:
  recipe-maintainers:
    - mdraw
    - aleju
