travis:
  secure:
    BINSTAR_TOKEN: Lk0FbKiZfFeRLs6c/sllMVeEesTfByRdHxly7YmT/k6WtwVpltx9Sm7aXbmrrdc9O96oTpkljr9vRFSQN25Qgz31Ha6bKI5+blz3Vdqm/W7gNichswjRfjXcgoZT0SnCCpN9L2vO5xdTH/S4c+kREgI24Omtn4qRxrdXMHsTjNgVUtEgNEj/CBhEmPud/fhDTjEfNMpluPw0S+sbs1A5Dn9pfHOHb4dSYtlV87pJSe/y2WSnuZC48Hns3oCKGg2IvdoHhycpSExl9uG4BzYZI4zXaz0hBq5CrAeLLXsl0Vv0qRnWDmQyA8bdllDTnMLbGxGs0p3qPwDdKeJ6jPFXy5WJroAOzC1Xle09Khk+OYWv/UgKawhTySqV9Shnpsb/IYp5jyaq/ka4jDW8emKkqEiy42axmFZkvz1P4Fp0/7sow3K1MFkbZ3byq0YZBaUX/d2dQ7QzIXRNbCJW+mkBIroo4Aqu3/a6tLFKfKBrjGlf3r2JtOhPgYx3vcTtGlCPNuBIqt5J02BbmSNTAGGCU/QW/rxlZWAkvyTgq6A55DTKepbG/bfeVQPLTY68lPPQjsLnrICiy6tQbpBEz40sEdpVuzXGn42DHDCjcVDGS/wo/uilSmVFG2iDVCR+XDBwsMQJcjDVD6uhonwhf2nBJVCdaA8Uf+VBQr0U1WdbFhw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
